UPDATE user u SET u.LOCATION_ID=LEFT(u.LOCATION_ID,1);
ALTER TABLE `hr_new`.`designation1` ADD COLUMN `ACTIVE` TINYINT(1) NOT NULL AFTER `DESIGNATION_DESC`;
CREATE TABLE `hr_new`.`mst_week_off_pattern` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESC` VARCHAR(45) NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`));
CREATE TABLE `hr_new`.`mst_week_off_count` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESC` VARCHAR(45) NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`));
CREATE TABLE `hr_new`.`mst_shift_duration` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESC` VARCHAR(45) NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`));
INSERT INTO mst_week_off_pattern VALUES (1, "Fixed", 1), (2, "Rotational", 1);
INSERT INTO mst_week_off_count VALUES (1, "One Week off", 1), (2, "Two Week off", 1), (3, "One Week off + alternate saturday off", 1);
INSERT INTO mst_shift_duration VALUES (1, "4 Hours", 1), (2, "8 Hours", 1), (3, "8.5 Hours", 1), (4, "9 Hours", 1), (5, "9.5 Hours", 1), (6, "10 Hours", 1), (7, "10.5 Hours", 1);
UPDATE requisition r LEFT JOIN mst_week_off_pattern wop ON r.WEEK_OFF_PATTERN=wop.`DESC` SET r.WEEK_OFF_PATTERN=wop.ID;
UPDATE requisition r LEFT JOIN mst_week_off_count woc ON r.WEEK_OFF_COUNT=woc.`DESC` SET r.WEEK_OFF_COUNT=woc.ID;
UPDATE requisition r LEFT JOIN mst_shift_duration sd ON r.SHIFT_DURATION=sd.`DESC` SET r.SHIFT_DURATION=sd.ID;

ALTER TABLE `hr_new`.`requisition` 
CHANGE COLUMN `DEPARTMENT_ID` `DEPARTMENT_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `LOCATION_ID` `LOCATION_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `USER_ID` `BU_USER_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `EMPLOYMENT_ID` `EMPLOYMENT_TYPE_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `PROCESS_ID` `PROCESS_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `REQUISITION_PROCESS_CATEGORY_ID` `PROCESS_CATEGORY_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `RECRUTMENT_ID` `RECRUTMENT_TYPE_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `HIRING_COUNT` `HIRING_COUNT` INT UNSIGNED NOT NULL ,
CHANGE COLUMN `RECRUITMENT_LEVEL_ID` `RECRUITMENT_LEVEL_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `LANGUAGE_ID` `LANGUAGE_IDS` VARCHAR(250) NULL DEFAULT NULL ,
CHANGE COLUMN `TRANNING_DATE_START` `TRAINING_DATE_START` DATE NULL DEFAULT NULL ,
CHANGE COLUMN `SALLERY_BOND` `SALARY_BAND` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `QUALIFICATION_ID` `QUALIFICATION_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `TYPING_ID` `TYPING_SPEED_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `COMMUNICATION_ID` `COMMUNICATION_PROFICIENCY_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `RATIO_ID` `GENDER_RATIO_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `REQUISITION_STATUS_ID` `REQUISITION_STATUS_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `HR_BUFFER_COUNT` `HR_BUFFER_COUNT` INT NULL DEFAULT '0' ,
CHANGE COLUMN `CREATED_BY` `CREATED_BY` INT UNSIGNED NOT NULL ,
CHANGE COLUMN `LAST_MODOFIED_BY` `LAST_MODIFIED_BY` INT UNSIGNED NOT NULL ,
CHANGE COLUMN `WEEK_OFF_PATTERN` `WEEK_OFF_PATTERN_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `WEEK_OFF_COUNT` `WEEK_OFF_COUNT_ID` INT UNSIGNED NULL DEFAULT NULL ,
CHANGE COLUMN `SHIFT_DURATION` `SHIFT_DURATION_ID` INT UNSIGNED NULL DEFAULT NULL ;

ALTER TABLE `hr_new`.`location` 
RENAME TO  `hr_new`.`mst_location` ;
ALTER TABLE `hr_new`.`mst_location` DROP FOREIGN KEY `FK_location_role_id`;
ALTER TABLE `hr_new`.`mst_location` DROP COLUMN `ROLE_ID`, DROP INDEX `FK_location_role_id` ;
ALTER TABLE `hr_new`.`mst_location` CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT UNSIGNED NOT NULL ;
ALTER TABLE `hr_new`.`department` CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , CHANGE COLUMN `CREATED_BY` `CREATED_BY` INT UNSIGNED NOT NULL , CHANGE COLUMN `LAST_MODIFIED_BY` `LAST_MODIFIED_BY` INT UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_department` ;
ALTER TABLE `hr_new`.`designation` RENAME TO  `hr_new`.`designation_hr` ;
ALTER TABLE `hr_new`.`designation1` CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_designation` ;
ALTER TABLE `hr_new`.`employment_type` CHANGE COLUMN `EMPLOYMENT_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `EMPLOYMENT_TYPE` `DESC` VARCHAR(15) NULL DEFAULT NULL , CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_employment_type` ;
ALTER TABLE `hr_new`.`gender` CHANGE COLUMN `GENDER_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `GENDER_DESC` `DESC` VARCHAR(20) NOT NULL , RENAME TO  `hr_new`.`mst_gender` ;
ALTER TABLE `hr_new`.`gender_ratio` CHANGE COLUMN `RATIO_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `RATIO_PERCENTAGE` `DESC` VARCHAR(15) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_gender_ratio` ;
ALTER TABLE `hr_new`.`languages` CHANGE COLUMN `LANGUAGE_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `LANGUAGE_DESC` `DESC` VARCHAR(50) NULL DEFAULT NULL , RENAME TO  `hr_new`.`language` ;
ALTER TABLE `hr_new`.`language` RENAME TO  `hr_new`.`mst_language` ;

ALTER TABLE `hr_new`.`process` DROP COLUMN `PROCESS_GROUP_ID`,DROP COLUMN `PROCESS_TYPE`,DROP COLUMN `HAS_ACCESS`,DROP COLUMN `MANAGEMENT_HEAD`,DROP COLUMN `PROCESS_HEAD`,DROP COLUMN `SORT_ORDER`, CHANGE COLUMN `PRPOCESS_BELONG_USER_ID` `BU_MANAGER_ID` INT UNSIGNED NULL DEFAULT NULL , DROP INDEX `FK_process_process_group_id` ;
ALTER TABLE `hr_new`.`process` DROP COLUMN `PROCESS_CATEGORY`;
ALTER TABLE `hr_new`.`candidate_qualification` DROP FOREIGN KEY `FK_candidate_qualification_id`;
ALTER TABLE `hr_new`.`candidate_qualification` DROP INDEX `FK_candidate_qualification_id` ;
ALTER TABLE `hr_new`.`qualification` CHANGE COLUMN `QUALIFICATION_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `QUALIFICATION_DESC` `DESC` VARCHAR(100) NOT NULL , RENAME TO  `hr_new`.`mst_qualification` ;
ALTER TABLE `hr_new`.`recruitment_level` CHANGE COLUMN `RECRUITMENT_LEVEL_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `RECRUITMENT_LEVAL_NAME` `DESC` VARCHAR(45) NULL DEFAULT NULL , CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_recruitment_level` ;
ALTER TABLE `hr_new`.`recruitment_type` CHANGE COLUMN `RECRUTMENT_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `RECRUTMENT_TYPE` `DESC` VARCHAR(40) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_recruitment_type` ;
ALTER TABLE `hr_new`.`candidate` DROP FOREIGN KEY `FK_candidate_referral_id`,DROP FOREIGN KEY `FK_candidate_martial_status_id`,DROP FOREIGN KEY `FK_candidate_gender_id`;
ALTER TABLE `hr_new`.`candidate` DROP INDEX `FK_candidate_referral_id` ,DROP INDEX `FK_candidate_martial_status_id` ,DROP INDEX `FK_candidate_gender_id` ;
ALTER TABLE `hr_new`.`referral` CHANGE COLUMN `REFERRAL_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `REFERRAL_DESC` `DESC` VARCHAR(50) NOT NULL , RENAME TO  `hr_new`.`mst_referral` ;
ALTER TABLE `hr_new`.`requisition_process_category` CHANGE COLUMN `REQUISITION_PROCESS_CATEGORY_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `PROCESS_CATEGORY_DES` `DESC` VARCHAR(60) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_process_category` ;
ALTER TABLE `hr_new`.`requisition_quilification` CHANGE COLUMN `QUALIFICATION_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `QUALIFICATION_NAME` `DESC` VARCHAR(25) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_min_qualification` ;
ALTER TABLE `hr_new`.`requisition_status` CHANGE COLUMN `REQUISITION_STATUS_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `STATUS_NAME` `DESC` VARCHAR(15) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_requisition_status` ;
ALTER TABLE `hr_new`.`role` RENAME TO  `hr_new`.`us_role` ;
ALTER TABLE `hr_new`.`role_business_function` RENAME TO  `hr_new`.`us_role_business_function` ;
DROP TABLE `hr_new`.`site_location`;
ALTER TABLE `hr_new`.`zip` DROP FOREIGN KEY `FK_zip_state_id`,DROP FOREIGN KEY `FK_zip_last_modified_by`;
ALTER TABLE `hr_new`.`zip` DROP INDEX `FK_zip_last_modified_by` ,DROP INDEX `FK_zip_state_id` ;
ALTER TABLE `hr_new`.`state` DROP COLUMN `LAST_MODIFIED_BY`,DROP COLUMN `LAST_MODIFIED_DATE`,CHANGE COLUMN `STATE_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `STATE_NAME` `DESC` VARCHAR(50) NOT NULL , RENAME TO  `hr_new`.`mst_state` ;
ALTER TABLE `hr_new`.`city` DROP FOREIGN KEY `FK_city_state_id`;
ALTER TABLE `hr_new`.`city` DROP COLUMN `LAST_MODIFIED_DATE`, DROP COLUMN `LAST_MODIFIED_BY`, CHANGE COLUMN `CITY_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `CITY_DESC` `DESC` VARCHAR(25) NULL DEFAULT NULL , CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , DROP INDEX `FK_city_state_id`;
ALTER TABLE `hr_new`.`city` RENAME TO  `hr_new`.`mst_city`;
ALTER TABLE `hr_new`.`marital_status` CHANGE COLUMN `MARITAL_STATUS_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `MARITAL_STATUS_DESC` `DESC` VARCHAR(30) NOT NULL , RENAME TO  `hr_new`.`mst_marital_status` ;
ALTER TABLE `hr_new`.`stream` CHANGE COLUMN `STREAM_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , CHANGE COLUMN `STREAM_DESC` `DESC` VARCHAR(25) NOT NULL , CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_education_stream` ;
ALTER TABLE `hr_new`.`typing_speed` CHANGE COLUMN `TYPING_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `TYPE_SPEED` `DESC` VARCHAR(15) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_typing_speed` ;
ALTER TABLE `hr_new`.`user` CHANGE COLUMN `LOCATION_ID` `LOCATION_ID` INT UNSIGNED NOT NULL ;
ALTER TABLE `hr_new`.`user` CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL ,CHANGE COLUMN `EXPIRED` `EXPIRED` TINYINT(1) UNSIGNED NOT NULL ,CHANGE COLUMN `FAILED_ATTEMPTS` `FAILED_ATTEMPTS` TINYINT UNSIGNED NOT NULL ,CHANGE COLUMN `OUTSIDE_ACCESS` `OUTSIDE_ACCESS` TINYINT(1) UNSIGNED NOT NULL ,CHANGE COLUMN `CREATED_BY` `CREATED_BY` INT UNSIGNED NOT NULL ,CHANGE COLUMN `LAST_MODIFIED_BY` `LAST_MODIFIED_BY` INT UNSIGNED NOT NULL ,CHANGE COLUMN `ADD_IN_REQUSITION` `ADD_IN_REQUSITION` INT NULL ;
UPDATE user u set u.ADD_IN_REQUSITION=0 WHERE u.ADD_IN_REQUSITION IS NULL;
ALTER TABLE `hr_new`.`user` CHANGE COLUMN `ADD_IN_REQUSITION` `ADD_IN_REQUISITION` INT UNSIGNED NOT NULL ,CHANGE COLUMN `DEPARTMENT_ID` `DEPARTMENT_ID` INT UNSIGNED NULL DEFAULT 0 ;
ALTER TABLE `hr_new`.`user_role` DROP FOREIGN KEY `FK_user_role_userId`,DROP FOREIGN KEY `FK_user_role_roleId`;
ALTER TABLE `hr_new`.`user_role` DROP INDEX `FK_user_role_ROLE_ID` ,DROP INDEX `FK_user_role_USER_ID` ;
ALTER TABLE `hr_new`.`user` RENAME TO  `hr_new`.`us_user` ;
ALTER TABLE `hr_new`.`user_role` RENAME TO  `hr_new`.`us_user_role` ;
ALTER TABLE `hr_new`.`work` CHANGE COLUMN `WORK_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `WORK_NAME` `DESC` VARCHAR(20) NULL DEFAULT NULL , RENAME TO  `hr_new`.`mst_work` ;
ALTER TABLE `hr_new`.`written_communication_proficiency` CHANGE COLUMN `COMMUNICATION_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `COMMUNICATION_PRO` `DESC` VARCHAR(16) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_communication_proficiency` ;
ALTER TABLE `hr_new`.`can_create_roles` RENAME TO  `hr_new`.`us_can_create_roles` ;
ALTER TABLE `hr_new`.`us_role_business_function` DROP FOREIGN KEY `FK_role_business_function_ROLE_ID`,DROP FOREIGN KEY `FK_role_business_function_BUSINESS_FUNCTION_ID`;
ALTER TABLE `hr_new`.`us_role_business_function` DROP INDEX `FK_role_business_function_BUSINESS_FUNCTION_ID` ,DROP INDEX `FK_role_business_function_ROLE_ID` ;
ALTER TABLE `hr_new`.`business_function` RENAME TO  `hr_new`.`us_business_function` ;
DROP TABLE `hr_new`.`access_log`;
DROP TABLE `hr_new`.`system_log`;
ALTER TABLE `hr_new`.`process` RENAME TO  `hr_new`.`mst_process` ;
ALTER TABLE `hr_new`.`requisition_final_status` CHANGE COLUMN `REQUISITION_FINAL_STATUS_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `STATUS_DESCRIPTION` `DESC` VARCHAR(15) NULL DEFAULT NULL ,CHANGE COLUMN `ACTIVE` `ACTIVE` TINYINT(1) UNSIGNED NOT NULL , RENAME TO  `hr_new`.`mst_requisition_final_status` ;
DROP TABLE hr_new.has_location_access;
DROP TABLE `hr_new`.`language_preferences`;
DROP TABLE `hr_new`.`question`, `hr_new`.`question_category`, `hr_new`.`question_option`, `hr_new`.`question_type`;
ALTER TABLE `hr_new`.`mst_department` CHANGE COLUMN `DEPARTMENT_ID` `ID` INT NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `DEPARTMENT_DESC` `DESC` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_designation` CHANGE COLUMN `DESIGNATION_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `DESIGNATION_DESC` `DESC` VARCHAR(50) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`mst_employment_type` CHANGE COLUMN `ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ;
ALTER TABLE `hr_new`.`mst_gender` CHANGE COLUMN `ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ;
ALTER TABLE `hr_new`.`mst_location` CHANGE COLUMN `LOCATION_ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `LOCATION_NAME` `DESC` VARCHAR(250) NOT NULL ;
ALTER TABLE `hr_new`.`mst_process` CHANGE COLUMN `PROCESS_ID` `ID` INT NOT NULL AUTO_INCREMENT ,CHANGE COLUMN `PROCESS_CODE` `CODE` VARCHAR(10) NOT NULL ,CHANGE COLUMN `PROCESS_DESC` `DESC` VARCHAR(50) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`us_user` CHANGE COLUMN `EMAIL_ID` `EMAIL_ID` VARCHAR(50) NULL DEFAULT NULL AFTER `USER_ID`,CHANGE COLUMN `USERNAME` `NAME` VARCHAR(50) NOT NULL ;

ALTER TABLE `hr_new`.`mst_city` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(25) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`mst_communication_proficiency` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(16) NOT NULL ;
ALTER TABLE `hr_new`.`mst_department` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_designation` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_education_stream` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(25) NOT NULL ;
ALTER TABLE `hr_new`.`mst_employment_type` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(15) NOT NULL ;
ALTER TABLE `hr_new`.`mst_gender` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(20) NOT NULL ;
ALTER TABLE `hr_new`.`mst_gender_ratio` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(15) NOT NULL ;
ALTER TABLE `hr_new`.`mst_language` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`mst_location` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(250) NOT NULL ;
ALTER TABLE `hr_new`.`mst_marital_status` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(30) NOT NULL ;
ALTER TABLE `hr_new`.`mst_min_qualification` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(25) NOT NULL ;
ALTER TABLE `hr_new`.`mst_process` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_process_category` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(60) NOT NULL ;
ALTER TABLE `hr_new`.`mst_qualification` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(100) NOT NULL ;
ALTER TABLE `hr_new`.`mst_recruitment_level` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(45) NOT NULL ;
ALTER TABLE `hr_new`.`mst_recruitment_type` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(40) NOT NULL ;
ALTER TABLE `hr_new`.`mst_referral` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_requisition_final_status` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(15) NOT NULL ;
ALTER TABLE `hr_new`.`mst_requisition_status` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(15) NOT NULL ;
ALTER TABLE `hr_new`.`mst_shift_duration` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(45) NOT NULL ;
ALTER TABLE `hr_new`.`mst_state` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(50) NOT NULL ;
ALTER TABLE `hr_new`.`mst_typing_speed` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(15) NOT NULL ;
ALTER TABLE `hr_new`.`mst_week_off_count` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(45) NOT NULL ;
ALTER TABLE `hr_new`.`mst_week_off_pattern` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(45) NOT NULL ;
ALTER TABLE `hr_new`.`mst_work` CHANGE COLUMN `DESC` `DESCRIPTION` VARCHAR(20) NOT NULL ;
ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `QUALIFICATION_ID` `MIN_QUALIFICATION_ID` INT UNSIGNED NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `BU_USER_ID` `BU_MANAGER_ID` INT UNSIGNED NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `OPERATION_WINDOWS` `OPERATION_WINDOW` VARCHAR(200) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`requisition` DROP COLUMN `OTHER_QUALIFICATION`;
CREATE TABLE `requisition_trans` (
  `REQUISITION_TRANS_ID` int NOT NULL AUTO_INCREMENT,
  `REQUISITION_ID` int NOT NULL,
  `REQUISITION_UNIQUE_ID` varchar(20) DEFAULT NULL,
  `DEPARTMENT_ID` int unsigned DEFAULT NULL,
  `LOCATION_ID` int unsigned DEFAULT NULL,
  `BU_MANAGER_ID` int unsigned DEFAULT NULL,
  `EMPLOYMENT_TYPE_ID` int unsigned DEFAULT NULL,
  `PROCESS_ID` int unsigned DEFAULT NULL,
  `PROCESS_CATEGORY_ID` int unsigned DEFAULT NULL,
  `RECRUTMENT_TYPE_ID` int unsigned DEFAULT NULL,
  `HIRING_COUNT` int unsigned NOT NULL,
  `RECRUITMENT_LEVEL_ID` int unsigned DEFAULT NULL,
  `LANGUAGE_IDS` varchar(250) DEFAULT NULL,
  `TRAINING_DATE_START` date DEFAULT NULL,
  `SALARY_BAND` varchar(50) DEFAULT NULL,
  `MIN_QUALIFICATION_ID` int unsigned DEFAULT NULL,
  `TYPING_SPEED_ID` int unsigned DEFAULT NULL,
  `COMMUNICATION_PROFICIENCY_ID` int unsigned DEFAULT NULL,
  `GENDER_RATIO_ID` int unsigned DEFAULT NULL,
  `COMMENTS` text,
  `REQUISITION_STATUS_ID` int unsigned DEFAULT NULL,
  `HR_BUFFER_COUNT` int DEFAULT '0',
  `HR_COMMENT` varchar(200) DEFAULT NULL,
  `HR_CLOSING_DATE` varchar(20) DEFAULT NULL,
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `LAST_MODIFIED_BY` int unsigned NOT NULL,
  `OPERATION_WINDOW` varchar(200) DEFAULT NULL,
  `WEEK_OFF_PATTERN_ID` int unsigned DEFAULT NULL,
  `WEEK_OFF_COUNT_ID` int unsigned DEFAULT NULL,
  `SHIFT_DURATION_ID` int unsigned DEFAULT NULL,
  PRIMARY KEY (`REQUISITION_TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TRIGGER IF EXISTS `hr_new`.`requisition_AFTER_INSERT`;

DELIMITER $$
USE `hr_new`$$
CREATE DEFINER = CURRENT_USER TRIGGER `hr_new`.`requisition_AFTER_INSERT` AFTER INSERT ON `requisition` FOR EACH ROW
BEGIN
    INSERT INTO `hr_new`.`requisition_trans`
        (`REQUISITION_ID`, `HIRING_COUNT`, `TRAINING_DATE_START`, `COMMENTS`, `REQUISITION_STATUS_ID`,
        `HR_BUFFER_COUNT`, `HR_COMMENT`, `HR_CLOSING_DATE`, `LAST_MODIFIED_DATE`, `LAST_MODIFIED_BY`) 
    VALUES
        (NEW.REQUISITION_ID, NEW.HIRING_COUNT, NEW.TRAINING_DATE_START, NEW.COMMENTS, NEW.REQUISITION_STATUS_ID, 
        NEW.HR_BUFFER_COUNT, NEW.HR_COMMENT, NEW.HR_CLOSING_DATE, NEW.LAST_MODIFIED_DATE, NEW.LAST_MODIFIED_BY);
    END$$
DELIMITER ;


DROP TRIGGER IF EXISTS `hr_new`.`requisition_AFTER_UPDATE`;

DELIMITER $$
USE `hr_new`$$
CREATE DEFINER = CURRENT_USER TRIGGER `hr_new`.`requisition_AFTER_UPDATE` AFTER INSERT ON `requisition` FOR EACH ROW
BEGIN
    INSERT INTO `hr_new`.`requisition_trans`
        (`REQUISITION_ID`, `HIRING_COUNT`, `TRAINING_DATE_START`, `COMMENTS`, `REQUISITION_STATUS_ID`,
        `HR_BUFFER_COUNT`, `HR_COMMENT`, `HR_CLOSING_DATE`, `LAST_MODIFIED_DATE`, `LAST_MODIFIED_BY`) 
    VALUES
        (NEW.REQUISITION_ID, NEW.HIRING_COUNT, NEW.TRAINING_DATE_START, NEW.COMMENTS, NEW.REQUISITION_STATUS_ID, 
        NEW.HR_BUFFER_COUNT, NEW.HR_COMMENT, NEW.HR_CLOSING_DATE, NEW.LAST_MODIFIED_DATE, NEW.LAST_MODIFIED_BY);
    END$$
DELIMITER ;


ALTER TABLE `hr_new`.`requisition_trans`  DROP COLUMN `SHIFT_DURATION_ID`, DROP COLUMN `WEEK_OFF_COUNT_ID`, DROP COLUMN `WEEK_OFF_PATTERN_ID`, DROP COLUMN `OPERATION_WINDOW`, DROP COLUMN `GENDER_RATIO_ID`, 
    DROP COLUMN `COMMUNICATION_PROFICIENCY_ID`, DROP COLUMN `TYPING_SPEED_ID`, DROP COLUMN `MIN_QUALIFICATION_ID`, DROP COLUMN `SALARY_BAND`, DROP COLUMN `LANGUAGE_IDS`, DROP COLUMN `RECRUITMENT_LEVEL_ID`, 
    DROP COLUMN `RECRUTMENT_TYPE_ID`, DROP COLUMN `PROCESS_CATEGORY_ID`, DROP COLUMN `PROCESS_ID`, DROP COLUMN `EMPLOYMENT_TYPE_ID`, DROP COLUMN `BU_MANAGER_ID`, DROP COLUMN `LOCATION_ID`, DROP COLUMN `DEPARTMENT_ID`,
    DROP COLUMN `REQUISITION_UNIQUE_ID`;


ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `HR_COMMENT` `HR_COMMENTS` VARCHAR(200) NULL DEFAULT NULL ;
ALTER TABLE `hr_new`.`requisition_trans` CHANGE COLUMN `HR_COMMENT` `HR_COMMENTS` VARCHAR(200) NULL DEFAULT NULL ;

DROP TRIGGER IF EXISTS `hr_new`.`requisition_AFTER_INSERT`;

DELIMITER $$
USE `hr_new`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `requisition_AFTER_INSERT` AFTER INSERT ON `requisition` FOR EACH ROW BEGIN
    INSERT INTO `hr_new`.`requisition_trans`
        (`REQUISITION_ID`, `HIRING_COUNT`, `TRAINING_DATE_START`, `COMMENTS`, `REQUISITION_STATUS_ID`,
        `HR_BUFFER_COUNT`, `HR_COMMENTS`, `HR_CLOSING_DATE`, `LAST_MODIFIED_DATE`, `LAST_MODIFIED_BY`) 
    VALUES
        (NEW.REQUISITION_ID, NEW.HIRING_COUNT, NEW.TRAINING_DATE_START, NEW.COMMENTS, NEW.REQUISITION_STATUS_ID, 
        NEW.HR_BUFFER_COUNT, NEW.HR_COMMENTS, NEW.HR_CLOSING_DATE, NEW.LAST_MODIFIED_DATE, NEW.LAST_MODIFIED_BY);
    END$$
DELIMITER ;


DROP TRIGGER IF EXISTS `hr_new`.`requisition_AFTER_UPDATE`;

DELIMITER $$
USE `hr_new`$$
CREATE DEFINER=`root`@`localhost` TRIGGER `requisition_AFTER_UPDATE` AFTER UPDATE ON `requisition` FOR EACH ROW BEGIN
INSERT INTO `hr_new`.`requisition_trans`
        (`REQUISITION_ID`, `HIRING_COUNT`, `TRAINING_DATE_START`, `COMMENTS`, `REQUISITION_STATUS_ID`,
        `HR_BUFFER_COUNT`, `HR_COMMENTS`, `HR_CLOSING_DATE`, `LAST_MODIFIED_DATE`, `LAST_MODIFIED_BY`) 
    VALUES
        (NEW.REQUISITION_ID, NEW.HIRING_COUNT, NEW.TRAINING_DATE_START, NEW.COMMENTS, NEW.REQUISITION_STATUS_ID, 
        NEW.HR_BUFFER_COUNT, NEW.HR_COMMENTS, NEW.HR_CLOSING_DATE, NEW.LAST_MODIFIED_DATE, NEW.LAST_MODIFIED_BY);
    END$$
DELIMITER ;

ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `EMPLOYMENT_TYPE_ID` `EMPLOYEE_TYPE_ID` INT UNSIGNED NULL DEFAULT NULL , CHANGE COLUMN `RECRUTMENT_TYPE_ID` `RECRUITMENT_TYPE_ID` INT UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `hr_new`.`requisition` CHANGE COLUMN `EMPLOYEE_TYPE_ID` `EMPLOYMENT_TYPE_ID` INT UNSIGNED NULL DEFAULT NULL;


